---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nath
  labels:
    app: nath
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nath
  template:
    metadata:
      labels:
        app: nath
    spec:
      containers:
        - name: nath
          image: docker.io/phengbunath/nath:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
